version: "3.8"

services:
  frontend:
    build: .
    container_name: ecom-frontend
    ports:
      - "5174:5174"
    command: npm run dev -- --host
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

