version: '3.8'

services:
  backend-container:
    build: .
    container_name: ecom
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://"yourcontainernameofmongodb":27017/ecomdb
      - JWT_SECRET= "your jwt key"  
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

